apiVersion: v1
kind: Service
metadata:
  name: {{ include "powerdns.fullname" . }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  labels:
{{ include "powerdns.labels" . | indent 4 }}
{{- with .Values.service.labels }}
{{ toYaml .}}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{ end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
{{- if (.Values.service.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.service.externalTrafficPolicy }}"
{{- end }}
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: dns-udp
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: dns-tcp
  selector:
    {{- include "powerdns.selectorLabels" . | nindent 4 }}
{{ if (.Values.powerdns.api_key) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "powerdns.fullname" . }}-webserver
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  labels:
{{ include "powerdns.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: dns-webserver
      protocol: TCP
  selector:
    {{- include "powerdns.selectorLabels" . | nindent 4 }}
{{- end }}
